# Generated by Django 5.1.3 on 2024-11-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenlandapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreview',
            name='designation',
        ),
    ]
