# Generated by Django 5.0.6 on 2024-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenlandapp', '0003_uvmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
