# Generated by Django 5.0.6 on 2024-12-08 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenlandapp', '0004_products_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shadecard',
            name='description',
        ),
        migrations.AddField(
            model_name='shadecard',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
