# Generated by Django 5.0.6 on 2024-12-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenlandapp', '0005_remove_shadecard_description_shadecard_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadecard',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
