# Generated by Django 5.1.3 on 2024-11-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenlandapp', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochure/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Date when the brochure was uploaded')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Date when the brochure was last updated')),
            ],
        ),
    ]
