# Generated by Django 5.1.3 on 2024-11-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenlandapp', '0007_pdfmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientReview',
        ),
    ]
